name: TraderStudio.Mobile CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
    DOTNET_VERSION: 8.0.x
    MOBILE_PROJECT: ./Src/RichillCapital.TraderStudio.Mobile/RichillCapital.TraderStudio.Mobile.csproj
    CONFIGURATION: Debug
    TARGET_FRAMEWORK: net8.0-android
    OUTPUT_DIRECTORY: ./artifacts

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Install MAUI Workloads
        run: dotnet workload install android

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ${{ env.MOBILE_PROJECT }} -c ${{ env.CONFIGURATION }} -f ${{ env.TARGET_FRAMEWORK }} --no-restore

      - name: Run Tests
        run: dotnet test -c ${{ env.CONFIGURATION }} -f ${{ env.TARGET_FRAMEWORK }} --no-restore --verbosity normal

      - name: Publish Android APK
        run: dotnet publish ${{ env.MOBILE_PROJECT }} -c ${{ env.CONFIGURATION }} -f ${{ env.TARGET_FRAMEWORK }} -o ${{ env.OUTPUT_DIRECTORY }} --no-restore 

      - name: Upload Artifact  
        uses: actions/upload-artifact@v4
        with:
          name: RichillCapital.TraderStudio.Mobile-1.0.0-Android-${{ env.CONFIGURATION }}
          path: ${{ env.OUTPUT_DIRECTORY }}/**/*Signed.apk