name: RichillCapital.TraderStudio.Mobile CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Keystore
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE }}" > richillcapital-traderstudio-mobile.asc
        gpg -d --passphrase ${{ secrets.GPG_PASSPHRASE }} --batch richillcapital-traderstudio-mobile.asc > richillcapital-traderstudio-mobile.keystore

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workloads
      run: dotnet workload install android
    
    - name: Restore Dependencies
      run: dotnet restore ./RichillCapital.TraderStudio.Mobile.sln

    - name: Build 
      run: dotnet build ./src/RichillCapital.TraderStudio.Mobile/RichillCapital.TraderStudio.Mobile.csproj -c Debug -f net8.0-android --no-restore -p:AndroidSigningKeyStore="./keys/richillcapital-traderstudio-mobile.keystore"  -p:AndroidSigningKeyAlias="richillcapital-traderstudio-mobile" -p:AndroidSigningKeyPass="${{ secrets.SIGNING_KEY_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}"
    
    - name: Tests
      run: dotnet test -c Debug -f net8.0 --no-restore --verbosity normal
    
    - name: Publish 
      run: dotnet publish ./src/RichillCapital.TraderStudio.Mobile/RichillCapital.TraderStudio.Mobile.csproj -c Debug -f net8.0-android -o ./artifact --no-restore -p:AndroidSigningKeyStore="./keys/richillcapital-traderstudio-mobile.keystore"  -p:AndroidSigningKeyAlias="richillcapital-traderstudio-mobile" -p:AndroidSigningKeyPass="${{ secrets.SIGNING_KEY_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RichillCapital.TraderStudio.Mobile-0.0.0-Android-Debug
        path: ./artifacts/**/*.apk